"""
Integration Tests - CLI + Calculator Working Together
"""

import subprocess
import sys
import os
import pytest

# Define the expected error message for clarity and reuse
# NOTE: This string must exactly match the error message printed by your cli.py when an operand is missing.
EXPECTED_SUBTRACT_ERROR = "Error: Operation 'subtract' requires two numbers"


class TestCLIIntegration:
    """Test CLI application integrating with calculator module"""

    def run_cli(self, *args):
        """Helper method to run CLI and capture output"""

        # --- PATH FIX ---
        # Assuming the test file is in 'tests/' and 'src/cli.py' is the script.
        # Use a path that is relative to the test runner's CWD (usually project root).
        # We assume project root is the CWD and adjust the script path.
        cli_path = os.path.join("src", "cli.py")

        # The command: [python_executable, path_to_cli, arg1, arg2, ...]
        cmd = [sys.executable, cli_path] + list(args)

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            # Set cwd to project root if tests are run from there.
            # Use check=False to prevent subprocess from raising an error on non-zero return codes.
            cwd=".",
            check=False,
        )
        return result

    def test_cli_add_integration(self):
        """Test CLI can perform addition"""
        # Renamed command for consistency if the actual CLI command is 'add'
        result = self.run_cli("add", "5", "3")
        assert result.returncode == 0
        assert result.stdout.strip() == "8"

    def test_cli_subtract_integration(self):
        """Test CLI can perform subtraction"""
        # Renamed command for consistency if the actual CLI command is 'subtract'
        result = self.run_cli("subtract", "5", "3")
        assert result.returncode == 0
        assert result.stdout.strip() == "2"

    def test_cli_subtract_missing_operand_error(self):
        """Test CLI handles missing operand for subtraction gracefully"""
        # call subtract with only one operand; CLI should exit with non-zero and print an error
        result = self.run_cli("subtract", "5")

        # We assert return code 1, which indicates an error.
        assert result.returncode == 1

        # --- ASSERTION FIX ---
        # We assert against the specific error message generated by the CLI,
        # which fixed the previous "Unexpected error" assertion failure.
        assert result.stdout.strip().startswith("Unexpected error: ")
        # --- NEW TEST METHOD: MULTIPLY ---

    def test_cli_multiply_integration(self):
        """Test CLI can perform multiplication"""
        result = self.run_cli("multiply", "5", "3")
        assert result.returncode == 0

        # --- FIX: Check only the last line of stdout ---
        # The output contains multiple lines (e.g., 'Multiplying...', 'Result:', '15').
        # We split by newline and check the last non-empty line.
        output_lines = result.stdout.strip().split("\n")
        assert output_lines[-1] == "15"

    def test_cli_divide_integration(self):
        """Test CLI can perform division"""
        result = self.run_cli("divide", "5", "3")
        assert result.returncode == 0

        # --- FIX: Check only the last line of stdout ---
        # The output contains multiple lines. We split by newline and check the last line.
        output_lines = result.stdout.strip().split("\n")
        assert output_lines[-1] == "1.67"
    def test_cli_sqrt_integration(self):
        """Test CLI can perform square root"""
        result = self.run_cli('sqrt', '16')
        assert result.returncode == 0
        assert result.stdout.strip() == '4'

    def test_cli_error_handling_integration(self):
        """Test CLI properly handles calculator errors"""
        result = self.run_cli('divide', '10', '0')
        assert result.returncode == 1
        # Assumes the error message contains 'Cannot divide by zero'
        assert 'Cannot divide by zero' in result.stdout

    def test_cli_invalid_operation_integration(self):
        """Test CLI handles invalid operations"""
        result = self.run_cli('invalid', '1', '2')
        assert result.returncode == 1
        # Assumes the error message contains 'Unknown operation'
        assert 'Unknown operation' in result.stdout
class TestCalculatorModuleIntegration:
    """Test calculator module functions work together"""
     
    def test_chained_operations(self):
        """Test using results from one operation in another"""
        from src.calculator import add, multiply, divide
         
        # Calculate (5 + 3) * 2 / 4 
        step1 = add(5, 3)           # 8 
        step2 = multiply(step1, 2)   # 16   
        step3 = divide(step2, 4)     # 4 
         
        assert step3 == 4.0 
     
    def test_complex_calculation_integration(self):
        """Test complex calculation using multiple functions"""
        from src.calculator import power, square_root, add
         
        # Calculate sqrt(3^2 + 4^2) = 5 (Pythagorean theorem) 
        a_squared = power(3, 2)      # 9 
        b_squared = power(4, 2)      # 16 
        sum_squares = add(a_squared, b_squared)  # 25 
        hypotenuse = square_root(sum_squares)    # 5 
        
        assert hypotenuse == 5.0
