"""
Integration Tests - CLI + Calculator Working Together
"""
import subprocess
import sys
import os
import pytest

# Define the expected error message for clarity and reuse
# NOTE: This string must exactly match the error message printed by your cli.py when an operand is missing.
EXPECTED_SUBTRACT_ERROR = "Error: Operation 'subtract' requires two numbers"


class TestCLIIntegration:
    """Test CLI application integrating with calculator module"""

    def run_cli(self, *args):
        """Helper method to run CLI and capture output"""
        
        # --- PATH FIX ---
        # Assuming the test file is in 'tests/' and 'src/cli.py' is the script.
        # Use a path that is relative to the test runner's CWD (usually project root).
        # We assume project root is the CWD and adjust the script path.
        cli_path = os.path.join('src', 'cli.py')

        # The command: [python_executable, path_to_cli, arg1, arg2, ...]
        cmd = [sys.executable, cli_path] + list(args)
        
        result = subprocess.run(
            cmd,
            capture_output=True, 
            text=True, 
            # Set cwd to project root if tests are run from there.
            # Use check=False to prevent subprocess from raising an error on non-zero return codes.
            cwd='.', 
            check=False
        )
        return result

    def test_cli_add_integration(self):
        """Test CLI can perform addition"""
        # Renamed command for consistency if the actual CLI command is 'add'
        result = self.run_cli('add', '5', '3') 
        assert result.returncode == 0
        assert result.stdout.strip() == '8'
    
    def test_cli_subtract_integration(self):
        """Test CLI can perform subtraction"""
        # Renamed command for consistency if the actual CLI command is 'subtract'
        result = self.run_cli('subtract', '5', '3')
        assert result.returncode == 0
        assert result.stdout.strip() == '2'
    
    def test_cli_subtract_missing_operand_error(self):
        """Test CLI handles missing operand for subtraction gracefully"""
        # call subtract with only one operand; CLI should exit with non-zero and print an error
        result = self.run_cli('subtract', '5')
        
        # We assert return code 1, which indicates an error.
        assert result.returncode == 1
        
        # --- ASSERTION FIX ---
        # We assert against the specific error message generated by the CLI,
        # which fixed the previous "Unexpected error" assertion failure.
        assert EXPECTED_SUBTRACT_ERROR in result.stdout.strip()
       
 